fix(ci-tests): clean version for appimage; added test when renaming appimage

diff --git a/.github/workflows/ci-run-tests.yml b/.github/workflows/ci-run-tests.yml
--- a/.github/workflows/ci-run-tests.yml
+++ b/.github/workflows/ci-run-tests.yml
@@ -66,7 +66,13 @@ jobs:
 
       - name: Add vesyla to PATH
         run: |
-          cp ${{ github.workspace }}/artifacts/vesyla-*.AppImage vesyla
+          set -e
+          file=(/home/gh-runner/actions-runner/_work/vesyla/vesyla/artifacts/vesyla-*.AppImage)
+          if [ "${#file[@]}" -ne 1 ]; then
+            echo "Error: Expected exactly one vesyla-*.AppImage file, found ${#file[@]}"
+            exit 1
+          fi
+          cp "${file[0]}" vesyla
           chmod a+x vesyla
           mkdir -p $HOME/.local/bin
           mv vesyla $HOME/.local/bin
